#!/usr/bin/env bash
pushd .
imgfile="/tmp/screenshot.png"
rm ${imgfile}
imlib2_grab -w 3840 -h 2160 ${imgfile}
# import -window root -density 3840x2160 -quality 80 ${imgfile}

./imblur -i "${imgfile}" -o "${imgfile}" -r 11 -c 69 -q yes
i3lock -t -i "${imgfile}"
# feh "${imgfile}"
popd || exit