#!/usr/bin/env bash
pushd .
imgfile="/tmp/screenshot.png"
rm ${imgfile}
imlib2_grab -noshape -w 3840 -h 2160 ${imgfile}
# import -window root -density 3840x2160 -depth 8 -quality 40 ${imgfile}
for i in {0..5}
do
./imblur -i "${imgfile}" -o "${imgfile}" -r 3 -c 5 -q yes

done
i3lock -t -i "${imgfile}"
# feh "${imgfile}"
popd || exit