on: [push]
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: before_script
        run: |
            sudo apt-get update
            sudo apt-get -y install clang cmake libboost-all-dev libopencv-dev graphviz doxygen git zip libspdlog-dev openssh-client
            git submodule sync --recursive &&
            git submodule update --init --recursive &&
            cd spdlog && cmake -B build && cmake --build build --target install -- -j4
      - name: script
        run: |
          cmake -B build
          cmake --build build
  
  doc:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: before_script
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive

      - name: script
        run: |
          cmake -B build
          cmake --build build --target Documentation
      - name: after_script
        run: | 
          mkdir -p public
          scripts/publish-to-public.sh